from multiprocessing import Pool
import os
from time import sleep

"""
kNN_arg.py help:
-c = catalogue type. 0 = deep (complete). 1 = wide (complete). 2 = full (missing values).
-f = replace missing values method. 0 = column mean. 1 = column median.
-t = training sample method. 0 = random. 1 = training on ELAIS-S1. 2 = training on eCDFS
-C = features to use. 0 = radio, sIndex, 3.6, 4.5, 5.8, 8.0, g, r, i, z. 1 = radio, 3.6, 4.5, 5.8, 8.0, g, r, i, z. 2 = radio, 3.6, 4.5, g, r, i, z (emu-like)
-d = distance metric. 1 = manhattan. 2 = euclidean. 99 = mahalonbis
-b = boostrap size. How many intervals (should use 1000+)
-p = pre-bin data. *shouldn't* be required for classification, but do it anyway just in case. Any input triggers.
-P = post-bin. any input triggers
-z = classification. any input triggers
-m = metric learn. Any input triggers
-M = method. 0 for kNN, 1 for linear/logistic regression, 2 for random forest, 3 for lasso regression, 4 for ridge regression.
"""


tests = []
##kNN Tests:
#tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 1 -b 1000")
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 1 -p True -z True")
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 0 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 1 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 2 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 0 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 1 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 2 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 0 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 1 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 2 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 0 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 1 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 1 -t 2 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 0 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 1 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 1 -t 2 -c 0 -f 1 -p True -z True") 


# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -p True -z True") 

# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 0 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 0 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 0 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 0 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 1 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 2 -c 1 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 0 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 1 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 2 -c 1 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 0 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 1 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 2 -c 1 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 0 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 1 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 99 -t 2 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 0 -f 1 -b 1000") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 0 -f 1 -b 1000 -p True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 0 -f 1 -b 1000 -P True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 0 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 1 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 0 -f 1 -p True -z True") 

# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 2 -f 0 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 2 -f 0 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 2 -f 0 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 0 -c 1 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 1 -c 1 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 2 -d 2 -t 2 -c 1 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -b 1000 -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -b 1000 -p True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -b 1000 -P True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 0 -c 0 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 1 -c 0 -f 1 -p True -z True -m True") 
# tests.append("python kNN_arg.py -M 0 -C 1 -d 2 -t 2 -c 0 -f 1 -p True -z True -m True") 

# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 0 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 1 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 2 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 0 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 1 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 2 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 0 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 1 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 2 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 0 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 1 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 2 -d 2 -t 2 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 0 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 1 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 2 -C 1 -d 2 -t 2 -c 0 -f 1 -p True -z True") 

# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 2 -f 0 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 0 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 1 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 2 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 0 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 1 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 2 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 0 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 1 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 2 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 0 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 1 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 2 -d 2 -t 2 -c 1 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 0 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 1 -c 0 -f 1 -p True -z True") 
# tests.append("python kNN_arg.py -M 1 -C 1 -d 2 -t 2 -c 0 -f 1 -p True -z True") 

# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 0 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 1 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 2 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 0 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 1 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 2 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 0 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 1 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 2 -d 2 -t 2 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 0 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 1 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 3 -C 1 -d 2 -t 2 -c 0 -f 1 -P True") 

# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 2 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 2 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 2 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 2 -f 0") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 2 -f 0 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 2 -f 0 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 0 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 1 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 2 -c 1 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 0 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 1 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 2 -c 1 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 0 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 1 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 2 -d 2 -t 2 -c 1 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 0 -f 1") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 0 -f 1 -p True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 0 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 1 -c 0 -f 1 -P True") 
# tests.append("python kNN_arg.py -M 4 -C 1 -d 2 -t 2 -c 0 -f 1 -P True") 





tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 0 -f 1 -z True")
#tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 1 -p True -b 1000")
#tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 0 -b 1000")
#tests.append("python kNN_arg.py -M 0 -C 1 -d 99 -t 2 -c 2 -f 0 -p True -b 1000")



def processTests(test):
#  sleep(3)
 os.system(test)

if __name__ == '__main__':
 pool = Pool(os.cpu_count())       # Create a multiprocessing Pool
 pool.map(processTests, tests) # process data_inputs iterable with pool
 pool.close()
 pool.join()
#  for i in range(len(tests)):
#   os.system(tests[i])